language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot flask pymongo aiohttp

script:
  - chmod +x * && chmod +x RAGNAROK && python3 RAGNAROK.py 
  from flask import Flask, render_template
from threading import Thread

app = Flask(__name__)
@app.route('/')
def index():
    return "Alive"

def run():
    app.run(host='0.0.0.0',port=8080)

def keep_alive():
    t = Thread(target=run)
    t.start()    
